apiVersion: v1
kind: Service
metadata:
  name: booking-service
  labels:
    app: booking-service
spec:
  # Use LoadBalancer to expose externally in Azure (AKS). 
  # Use ClusterIP if you only want it accessible inside the cluster (e.g. via an API Gateway)
  type: ClusterIP
  selector:
    app: booking-service
  ports:
    - protocol: TCP
      port: 80         # The external port exposed to the internet
      targetPort: 5001 # The port your Node.js app runs on inside the container
